### Q1. Import the Numpy package under the name np

In [1]:
import numpy as np

### Q2. Create a null vector of size 10

In [2]:
import numpy as np
x = np.zeros(10)
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


### Q3. Create a null vector of size 10 but the fifth value which is 1

In [3]:
y = np.zeros(10)
y[4] = 1
print(y)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


### Q4. Create a vector with values ranging from 10 to 49

In [4]:
ranged_vector = np.arange(10, 50)
print(ranged_vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


### Q5. Reverse a vector (the first element becomes last)

In [5]:
original_vector = np.arange(2, 8)
print(original_vector)

#slicing with reverse direction, step size 1 and assigning to the same vector
reversed_vector = original_vector[::-1]
print(reversed_vector)

[2 3 4 5 6 7]
[7 6 5 4 3 2]


### Q6. Create a 3x3 matrix with values ranging from 0 to 8

In [6]:
matrix = np.arange(0, 9).reshape(3,3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


### Q7. Find indices of non­zero elements from [1,2,0,0,4,0]

In [7]:
given_array = np.array([1,2,0,0,4,0])
print("given array: ")
print(given_array)
print("Indices of elements not equal to zero of the given array:")
non_zero_indices = np.where(given_array != 0)[0]
print(non_zero_indices)

given array: 
[1 2 0 0 4 0]
Indices of elements not equal to zero of the given array:
[0 1 4]


### Q8. Create a 3x3x3 array with random values

In [8]:
random3x3x3_array = np.random.random((3,3,3))
print(random3x3x3_array)

[[[0.58408433 0.10219923 0.95513179]
  [0.32787389 0.226085   0.72722771]
  [0.62500416 0.58595776 0.86808018]]

 [[0.76089442 0.36255481 0.61571256]
  [0.63420534 0.3520453  0.799209  ]
  [0.33256015 0.81862098 0.10508659]]

 [[0.82990926 0.24379221 0.87671934]
  [0.83540056 0.24059761 0.291678  ]
  [0.98549258 0.98316592 0.32936614]]]


### Q9. Create a random vector of size 30 and find the mean value

In [9]:
vector_y = np.random.random(30)
mean_y = np.mean(vector_y)
print(mean_y)

0.493874166552231


### Q.10 Create a 2d array with 1 on the border and 0 inside

In [10]:
x = np.ones((5,5))
print("Original array:")
print(x)
print("\n 1 on the border and 0 inside in the array \n")
x[1:-1,1:-1] = 0
print(x)

Original array:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

 1 on the border and 0 inside in the array 

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


### Q.11 Create an 8x8 matrix and fill it with a checkerboard pattern

In [11]:
# checkboard = np.ones((3,3))
print("Checkerboard pattern using ones and zeroes:")
checkboard = np.zeros((8,8),dtype=int)
print('Intialised a null checkboard as shown below:')
print(checkboard)
#slice adding value 1 with step=2(every 2nd) starting from row index 1 with all columns starting from 0th
checkboard[1::2,::2] = 1
#slice adding value 1 with step=2(every 2nd) starting from row index 0 with all columns starting from 1st
checkboard[0::2,1::2] = 1
print('\nFinal checkboard')
print(checkboard)

Checkerboard pattern using ones and zeroes:
Intialised a null checkboard as shown below:
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]

Final checkboard
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


### Q.12 What is the major difference between sets, lists, tuples and dictionaries?

##### Answer:


### Q13. Print first 10 natural numbers using while loop

In [12]:
print('First 10 Natural numbers are as follows : ')
counter = 1
while counter <= 10:
    print(counter)
    counter += 1

First 10 Natural numbers are as follows : 
1
2
3
4
5
6
7
8
9
10


### Q14. Print the numbers -10 to -1 using for loop.

In [13]:
for number in range(-10, 0, 1):
    print(number)

-10
-9
-8
-7
-6
-5
-4
-3
-2
-1


### Q15. Print the message “Done” after successful execution of any for a loop.

In [14]:
for number in range(-10, 0, 1):
    print(number)
    
print('Done')

-10
-9
-8
-7
-6
-5
-4
-3
-2
-1
Done


### Q16. Create a random vector of size 10 and sort it

In [15]:
z = np.random.random(10)
print("Original random vector:")
print(z)
z.sort()
print("Sorted random vector:")
print(z)

Original random vector:
[0.47404798 0.56155237 0.2066734  0.84688436 0.79559203 0.2384116
 0.16577919 0.97326589 0.80211136 0.945296  ]
Sorted random vector:
[0.16577919 0.2066734  0.2384116  0.47404798 0.56155237 0.79559203
 0.80211136 0.84688436 0.945296   0.97326589]


### Q17. Execute any three math functions using NumPy.

In [16]:
#Ceiling function : 
print('ceiling function')
p = np.array([-2.7, 1.2, -0.23, 14.6, 10]) 

print('The given array: ')
print(p)
 
print('\nThe modified array: ')
print(np.ceil(p))

#floor function
print('\nfloor function')
q = np.array([-2.7, 1.2, -0.23, 14.6, 10]) 

print('The given array: ')
print(q)

print('\nThe modified array: ')
print(np.floor(q))


#Rounding function : around
print('\nRounding function')
r = np.array([-2.7, 1.2, -0.23, 14.6, 10])

print('Original array: ')
print(r)   

print('\nAfter rounding:')
print(np.around(r)) 
print(np.around(r, decimals = 1)) 
print(np.around(r, decimals = -1))

ceiling function
The given array: 
[-2.7   1.2  -0.23 14.6  10.  ]

The modified array: 
[-2.  2. -0. 15. 10.]

floor function
The given array: 
[-2.7   1.2  -0.23 14.6  10.  ]

The modified array: 
[-3.  1. -1. 14. 10.]

Rounding function
Original array: 
[-2.7   1.2  -0.23 14.6  10.  ]

After rounding:
[-3.  1. -0. 15. 10.]
[-2.7  1.2 -0.2 14.6 10. ]
[-0.  0. -0. 10. 10.]
